admin_mail_list:
    path:   /settings/mail
    controller: Pd\MailerBundle\Controller\MailController::list
    methods: [GET]
admin_mail_template_add:
    path: /settings/mail/add/{id}
    controller: Pd\MailerBundle\Controller\MailController::addTemplate
    methods: [GET, POST]
    defaults:
        id: null
admin_mail_template_edit:
    path: /settings/mail/edit/{id}
    controller: Pd\MailerBundle\Controller\MailController::editTemplate
    methods: [GET, POST]
admin_mail_template_delete:
    path: /settings/mail/delete/{id}
    controller: Pd\MailerBundle\Controller\MailController::deleteTemplate
    methods: [GET]
admin_mail_template_activate:
    path: /settings/mail/activate/{id}
    controller: Pd\MailerBundle\Controller\MailController::activeTemplate
    methods: [GET]
admin_mail_logger:
    path:   /settings/mail/logger
    controller: Pd\MailerBundle\Controller\MailController::logger
    methods: [GET]
admin_mail_logview:
    path:   /settings/mail/logview/{id}
    controller: Pd\MailerBundle\Controller\MailController::viewLog
    methods: [GET]
admin_mail_logdelete:
    path:   /settings/mail/logdelete/{mailLog}
    controller: Pd\MailerBundle\Controller\MailController::deleteLog
    defaults:
        mailLog: null
    methods: [POST,GET]
